const pool = require('../config/db');

/**
 * Order Data Access Layer
 * Handles order and order_items database operations
 */

/**
 * Map database row to order object with camelCase naming
 */
function mapOrderRow(row) {
  if (!row) return null;
  
  return {
    id: row.id,
    userId: row.user_id,
    firebaseUid: row.firebase_uid,
    orderNumber: row.order_number,
    totalAmount: parseFloat(row.total_amount),
    paymentMethod: row.payment_method,
    paymentStatus: row.payment_status,
    orderStatus: row.order_status,
    deliveryAddress: row.delivery_address,
    notes: row.notes,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

/**
 * Map database row to order item object
 */
function mapOrderItemRow(row) {
  if (!row) return null;
  
  return {
    id: row.id,
    orderId: row.order_id,
    productId: row.product_id,
    productName: row.product_name,
    productSku: row.product_sku,
    quantity: parseInt(row.quantity, 10),
    unitPrice: parseFloat(row.unit_price),
    totalPrice: parseFloat(row.total_price),
    createdAt: row.created_at
  };
}

/**
 * Create order with order items in a transaction
 * Returns the created order with order items
 */
async function createOrder(orderData, orderItems, client = null) {
  const shouldManageTransaction = !client;
  const dbClient = client || await pool.connect();
  
  try {
    if (shouldManageTransaction) {
      await dbClient.query('BEGIN');
    }
    
    // Insert order (order_number will be auto-generated by trigger)
    const orderQuery = `
      INSERT INTO orders (
        user_id, firebase_uid, total_amount, payment_method, 
        payment_status, order_status, delivery_address, notes
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      RETURNING *;
    `;
    
    const orderValues = [
      orderData.userId,
      orderData.firebaseUid,
      orderData.totalAmount,
      orderData.paymentMethod || 'COD',
      orderData.paymentStatus || 'pending',
      orderData.orderStatus || 'pending',
      JSON.stringify(orderData.deliveryAddress),
      orderData.notes || null
    ];
    
    const orderResult = await dbClient.query(orderQuery, orderValues);
    const order = mapOrderRow(orderResult.rows[0]);
    
    // Insert order items
    const itemsToInsert = [];
    for (const item of orderItems) {
      const itemQuery = `
        INSERT INTO order_items (
          order_id, product_id, product_name, product_sku,
          quantity, unit_price, total_price
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING *;
      `;
      
      const itemValues = [
        order.id,
        item.productId,
        item.productName,
        item.productSku,
        item.quantity,
        item.unitPrice,
        item.totalPrice
      ];
      
      const itemResult = await dbClient.query(itemQuery, itemValues);
      itemsToInsert.push(mapOrderItemRow(itemResult.rows[0]));
    }
    
    if (shouldManageTransaction) {
      await dbClient.query('COMMIT');
    }
    
    return {
      ...order,
      items: itemsToInsert
    };
  } catch (error) {
    if (shouldManageTransaction) {
      await dbClient.query('ROLLBACK');
    }
    throw error;
  } finally {
    if (shouldManageTransaction) {
      dbClient.release();
    }
  }
}

/**
 * Find order by ID with order items
 */
async function findOrderById(orderId) {
  const orderQuery = 'SELECT * FROM orders WHERE id = $1;';
  const orderResult = await pool.query(orderQuery, [orderId]);
  
  if (orderResult.rows.length === 0) {
    return null;
  }
  
  const order = mapOrderRow(orderResult.rows[0]);
  
  // Fetch order items
  const itemsQuery = 'SELECT * FROM order_items WHERE order_id = $1 ORDER BY created_at;';
  const itemsResult = await pool.query(itemsQuery, [orderId]);
  
  order.items = itemsResult.rows.map(mapOrderItemRow);
  
  return order;
}

/**
 * Find order by order number
 */
async function findOrderByOrderNumber(orderNumber) {
  const query = 'SELECT * FROM orders WHERE order_number = $1;';
  const result = await pool.query(query, [orderNumber]);
  
  if (result.rows.length === 0) {
    return null;
  }
  
  const order = mapOrderRow(result.rows[0]);
  
  // Fetch order items
  const itemsQuery = 'SELECT * FROM order_items WHERE order_id = $1 ORDER BY created_at;';
  const itemsResult = await pool.query(itemsQuery, [order.id]);
  
  order.items = itemsResult.rows.map(mapOrderItemRow);
  
  return order;
}

/**
 * Find orders by user ID with pagination and filters
 */
async function findOrdersByUserId(userId, { page = 1, limit = 20, status, dateFrom, dateTo } = {}) {
  const offset = (page - 1) * limit;
  const whereClauses = ['user_id = $1'];
  const queryParams = [userId];
  
  if (status) {
    queryParams.push(status);
    whereClauses.push(`order_status = $${queryParams.length}`);
  }
  
  if (dateFrom) {
    queryParams.push(new Date(dateFrom));
    whereClauses.push(`created_at >= $${queryParams.length}`);
  }
  
  if (dateTo) {
    queryParams.push(new Date(dateTo));
    whereClauses.push(`created_at <= $${queryParams.length}`);
  }
  
  const whereString = whereClauses.join(' AND ');
  
  // Count total
  const countQuery = `SELECT COUNT(*) FROM orders WHERE ${whereString};`;
  const countResult = await pool.query(countQuery, queryParams);
  const total = parseInt(countResult.rows[0].count, 10);
  
  // Fetch orders
  const dataParams = [...queryParams, limit, offset];
  const dataQuery = `
    SELECT * FROM orders
    WHERE ${whereString}
    ORDER BY created_at DESC
    LIMIT $${dataParams.length - 1} OFFSET $${dataParams.length};
  `;
  const dataResult = await pool.query(dataQuery, dataParams);
  
  const orders = dataResult.rows.map(mapOrderRow);
  
  // Fetch items for each order
  for (const order of orders) {
    const itemsQuery = 'SELECT * FROM order_items WHERE order_id = $1 ORDER BY created_at;';
    const itemsResult = await pool.query(itemsQuery, [order.id]);
    order.items = itemsResult.rows.map(mapOrderItemRow);
  }
  
  return {
    orders,
    total,
    page,
    limit
  };
}

/**
 * Find all orders with pagination and filters (admin view)
 */
async function findAllOrders({ page = 1, limit = 20, status, paymentStatus, dateFrom, dateTo, search } = {}) {
  const offset = (page - 1) * limit;
  const whereClauses = [];
  const queryParams = [];
  
  if (status) {
    queryParams.push(status);
    whereClauses.push(`order_status = $${queryParams.length}`);
  }
  
  if (paymentStatus) {
    queryParams.push(paymentStatus);
    whereClauses.push(`payment_status = $${queryParams.length}`);
  }
  
  if (dateFrom) {
    queryParams.push(new Date(dateFrom));
    whereClauses.push(`created_at >= $${queryParams.length}`);
  }
  
  if (dateTo) {
    queryParams.push(new Date(dateTo));
    whereClauses.push(`created_at <= $${queryParams.length}`);
  }
  
  if (search) {
    queryParams.push(`%${search}%`);
    whereClauses.push(`(order_number ILIKE $${queryParams.length} OR firebase_uid ILIKE $${queryParams.length})`);
  }
  
  const whereString = whereClauses.length > 0 ? `WHERE ${whereClauses.join(' AND ')}` : '';
  
  // Count total
  const countQuery = `SELECT COUNT(*) FROM orders ${whereString};`;
  const countResult = await pool.query(countQuery, queryParams);
  const total = parseInt(countResult.rows[0].count, 10);
  
  // Fetch orders
  const dataParams = [...queryParams, limit, offset];
  const dataQuery = `
    SELECT o.*, u.name as customer_name, u.email as customer_email
    FROM orders o
    LEFT JOIN users u ON o.user_id = u.id
    ${whereString}
    ORDER BY o.created_at DESC
    LIMIT $${dataParams.length - 1} OFFSET $${dataParams.length};
  `;
  const dataResult = await pool.query(dataQuery, dataParams);
  
  const orders = dataResult.rows.map(row => ({
    ...mapOrderRow(row),
    customerName: row.customer_name,
    customerEmail: row.customer_email
  }));
  
  // Fetch items for each order
  for (const order of orders) {
    const itemsQuery = 'SELECT * FROM order_items WHERE order_id = $1 ORDER BY created_at;';
    const itemsResult = await pool.query(itemsQuery, [order.id]);
    order.items = itemsResult.rows.map(mapOrderItemRow);
  }
  
  return {
    orders,
    total,
    page,
    limit
  };
}

/**
 * Update order status
 */
async function updateOrderStatus(orderId, status, notes = null) {
  const query = `
    UPDATE orders
    SET order_status = $1, notes = COALESCE($2, notes), updated_at = CURRENT_TIMESTAMP
    WHERE id = $3
    RETURNING *;
  `;
  
  const result = await pool.query(query, [status, notes, orderId]);
  
  if (result.rows.length === 0) {
    return null;
  }
  
  return mapOrderRow(result.rows[0]);
}

/**
 * Update payment status
 */
async function updatePaymentStatus(orderId, paymentStatus) {
  const query = `
    UPDATE orders
    SET payment_status = $1, updated_at = CURRENT_TIMESTAMP
    WHERE id = $2
    RETURNING *;
  `;
  
  const result = await pool.query(query, [paymentStatus, orderId]);
  
  if (result.rows.length === 0) {
    return null;
  }
  
  return mapOrderRow(result.rows[0]);
}

/**
 * Get order statistics for a user
 */
async function getUserOrderStats(userId) {
  const query = `
    SELECT 
      COUNT(*) as total_orders,
      COUNT(*) FILTER (WHERE order_status = 'pending') as pending_orders,
      COUNT(*) FILTER (WHERE order_status = 'confirmed') as confirmed_orders,
      COUNT(*) FILTER (WHERE order_status = 'delivered') as delivered_orders,
      COUNT(*) FILTER (WHERE order_status = 'completed') as completed_orders,
      COUNT(*) FILTER (WHERE order_status = 'cancelled') as cancelled_orders,
      COALESCE(SUM(total_amount) FILTER (WHERE order_status != 'cancelled'), 0) as total_spent
    FROM orders
    WHERE user_id = $1;
  `;
  
  const result = await pool.query(query, [userId]);
  
  return {
    totalOrders: parseInt(result.rows[0].total_orders, 10),
    pendingOrders: parseInt(result.rows[0].pending_orders, 10),
    confirmedOrders: parseInt(result.rows[0].confirmed_orders, 10),
    deliveredOrders: parseInt(result.rows[0].delivered_orders, 10),
    completedOrders: parseInt(result.rows[0].completed_orders, 10),
    cancelledOrders: parseInt(result.rows[0].cancelled_orders, 10),
    totalSpent: parseFloat(result.rows[0].total_spent)
  };
}

/**
 * Get order items by order ID
 */
async function getOrderItems(orderId) {
  const query = 'SELECT * FROM order_items WHERE order_id = $1 ORDER BY created_at;';
  const result = await pool.query(query, [orderId]);
  
  return result.rows.map(mapOrderItemRow);
}

module.exports = {
  createOrder,
  findOrderById,
  findOrderByOrderNumber,
  findOrdersByUserId,
  findAllOrders,
  updateOrderStatus,
  updatePaymentStatus,
  getUserOrderStats,
  getOrderItems,
  mapOrderRow,
  mapOrderItemRow
};
